//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Content {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Content() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Content", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Bi-weekly.
        /// </summary>
        internal static string AcceleratedBiWeekly {
            get {
                return ResourceManager.GetString("AcceleratedBiWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerated Weekly.
        /// </summary>
        internal static string AcceleratedWeekly {
            get {
                return ResourceManager.GetString("AcceleratedWeekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amortization Period.
        /// </summary>
        internal static string AmortizationPeriod {
            get {
                return ResourceManager.GetString("AmortizationPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AskStackOverFlow.
        /// </summary>
        internal static string AskStackOverFlow {
            get {
                return ResourceManager.GetString("AskStackOverFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bi-weekly.
        /// </summary>
        internal static string Biweekly {
            get {
                return ResourceManager.GetString("Biweekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate.
        /// </summary>
        internal static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        internal static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interest Rate.
        /// </summary>
        internal static string InterestRate {
            get {
                return ResourceManager.GetString("InterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Amount.
        /// </summary>
        internal static string MortgageAmount {
            get {
                return ResourceManager.GetString("MortgageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mortgage Calculator.
        /// </summary>
        internal static string MortgageCalculator {
            get {
                return ResourceManager.GetString("MortgageCalculator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Frequency.
        /// </summary>
        internal static string PaymentFrequency {
            get {
                return ResourceManager.GetString("PaymentFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-monthly.
        /// </summary>
        internal static string SemiMonthly {
            get {
                return ResourceManager.GetString("SemiMonthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SiteMap.
        /// </summary>
        internal static string SiteMap {
            get {
                return ResourceManager.GetString("SiteMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Over.
        /// </summary>
        internal static string StartOver {
            get {
                return ResourceManager.GetString("StartOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter interest rate in percentage.
        /// </summary>
        internal static string TipsInterestRate {
            get {
                return ResourceManager.GetString("TipsInterestRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter total mortgage amount.
        /// </summary>
        internal static string TipsMortgageAmount {
            get {
                return ResourceManager.GetString("TipsMortgageAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool.
        /// </summary>
        internal static string Tool {
            get {
                return ResourceManager.GetString("Tool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        internal static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
